version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      rljson:
        patterns:
          - '@rljson/*'
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@rljson/*'
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - '@rljson/*'

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /packages/node-service
    schedule:
      interval: weekly
