/**
 * The Duckburg name pools the generator draws persons, farms, addresses and
 * animals from. Persons and animals share no first names with the
 * hand-written seed's animals, so a search for a hand-written pet such as
 * "Donald" never turns up a generated one by accident.
 */

export const firstNames: readonly string[] = [
  'Della',
  'Huey',
  'Dewey',
  'Louie',
  'Webby',
  'Launchpad',
  'Gus',
  'Ludwig',
  'Clara',
  'Horace',
  'Emily',
  'Gilbert',
  'Abner',
  'Matilda',
  'Hortense',
  'Elvira',
  'Humperdink',
  'Gideon',
  'Cornelius',
  'Fenton',
  'Doofus',
  'April',
  'May',
  'June',
  'Brigitta',
  'Dickie',
  'Jubal',
  'Moby',
  'Rita',
  'Casey',
  'Cuthbert',
  'Prunella',
  'Lulubelle',
  'Bentina',
  'Goldie',
  'Angus',
  'Jake',
  'Pothole',
  'Millicent',
  'Dugan',
  'Ottoperotto',
  'Lena',
  'Violet',
  'Boyd',
  'Zan',
];

export const surnames: readonly string[] = [
  'Duck',
  'McDuck',
  'Gander',
  'Gearloose',
  'Glomgold',
  'Rockerduck',
  'Beagle',
  'Quackfaster',
  'Featherby',
  'Drake',
  'Mallard',
  'Webfoot',
  'Coot',
  'Gosling',
  'Pintail',
  'Teal',
  'Eider',
  'Wigeon',
  'Cluck',
  'Peck',
  'Plume',
  'Sprocket',
  'Whirligig',
  'McQuack',
  'Vanderquack',
  'Duckworth',
  'Beakley',
  "O'Gilt",
  'Crackshell',
  'Pennyfeather',
  'Sabrewing',
  'Featherstone',
  'Quackenbush',
  'Downyfield',
];

export const streets: readonly string[] = [
  'Killmotor Hill',
  'Webfoot Walk',
  'Lucky Lane',
  'Mockingbird Lane',
  'Tangleweed Trail',
  'Quackmore Farm Road',
  'Harbour Street',
  'Money Bin Plaza',
  'Audubon Bay Boulevard',
  'Gearloose Gulch',
  'Cornelius Coot Square',
  'Old Mill Road',
  'Lighthouse Lane',
  'Feathergate Avenue',
  'Duckville Drive',
  'Pier Nine',
  'Junkyard Row',
  'Quill Street',
  'Pond Street',
  'Woodchuck Way',
  'Vulture Peak Road',
  'Tulip Terrace',
];

/**
 * Where a generated person lives, weighted by repetition: most of Duckburg's
 * pet shop customers live in Duckburg itself, a few in the neighbouring
 * towns of the same universe.
 */
export const cities: readonly string[] = [
  'Duckburg',
  'Duckburg',
  'Duckburg',
  'Duckburg',
  'Duckburg',
  'Duckburg',
  'Mouseton',
  'Goosetown',
  'St. Canard',
];

/**
 * The kinds of establishment a generated breeder runs, each combined with
 * a surname (`Featherby Stables`, `Pintail's Pond`).
 */
export const farmKinds: readonly string[] = [
  'Farm',
  'Hatchery',
  'Kennels',
  'Stables',
  'Nursery',
  'Aviary',
  'Pond',
  'Ranch',
  'Meadows',
  'Burrow',
  'Paddock',
  'Coop',
  'Roost',
  'Warren',
  'Menagerie',
];

export const animalNames: readonly string[] = [
  'Waddles',
  'Biscuit',
  'Pippin',
  'Marmalade',
  'Sprocket',
  'Nugget',
  'Pumpkin',
  'Ginger',
  'Pebble',
  'Clover',
  'Doodle',
  'Ziggy',
  'Rusty',
  'Maple',
  'Bramble',
  'Tinker',
  'Widget',
  'Muffin',
  'Pickles',
  'Noodle',
  'Bubbles',
  'Peanut',
  'Truffle',
  'Waffles',
  'Gumbo',
  'Jasper',
  'Hazel',
  'Olive',
  'Cricket',
  'Dumpling',
  'Fig',
  'Goober',
  'Hobnob',
  'Inky',
  'Jellybean',
  'Kipper',
  'Lentil',
  'Mochi',
  'Nutmeg',
  'Otis',
  'Poppy',
  'Quibble',
  'Rumble',
  'Scooter',
  'Tater',
  'Umber',
  'Velvet',
  'Wobble',
  'Yodel',
  'Zephyr',
  'Bumble',
  'Chester',
  'Dobby',
  'Elmo',
  'Fergus',
  'Gizmo',
  'Hamish',
  'Igor',
  'Jinx',
  'Kiwi',
  'Lumpy',
  'Mabel',
  'Nibbles',
  'Ollie',
  'Pudding',
  'Rascal',
  'Sprout',
  'Toffee',
  'Whiskers',
  'Tuppence',
];

/**
 * The suffix a generated animal's name gets some of the time, in the style
 * of the hand-written pets ("Quackmore Junior", "Donald the Third").
 */
export const animalEpithets: readonly string[] = [
  'the Bold',
  'the Younger',
  'the Magnificent',
  'the Sleepy',
  'the Third',
  'of Killmotor Hill',
  'the Unlucky',
  'the Loud',
  'the Curious',
  'the Second',
  'the Great',
  'the Brave',
  'the Quiet',
  'Junior',
  'the Explorer',
  'the Dreamer',
  'the Wise',
  'of the Money Bin',
  'the Fearless',
  'the Champion',
];

/**
 * The Duckburg regulars a generated story can name, so that generated
 * pets, like the hand-written ones, cross paths with the people every
 * reader knows.
 */
export const duckburgRegulars: readonly string[] = [
  'Scrooge McDuck',
  'Donald Duck',
  'Gyro Gearloose',
  'the Beagle Boys',
  'Magica De Spell',
  'Grandma Duck',
  'Gladstone Gander',
  'Huey, Dewey and Louie',
  'Launchpad McQuack',
  'Daisy Duck',
  'Flintheart Glomgold',
  'John D. Rockerduck',
];
